
name: Publish minor version

on:
  # On push / merge to `main`
  push:
    branches: [ main ]
  # On demand
  workflow_dispatch:

env:
  TESTS_API_KEY: ${{ secrets.TESTS_API_KEY }}
  TESTS_FORCE_BASE_URL: ${{ secrets.TESTS_FORCE_BASE_URL }}
  NPM_ORG_TOKEN: ${{ secrets.NPM_ORG_TOKEN }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: "Install Node"
      uses: actions/setup-node@v2
      with:
        node-version: "18"
        registry-url: https://registry.npmjs.org/
    - name: "Install dependencies"
      run: npm install
    - name: "Run tests"
      run: npm run test
    - name: "Bump package version number"
      run: npm version minor
    - name: "Commit changes (if any)"
      run: |
        git config user.email "lil@law.harvard.edu";
        git config user.name "Github Actions"; 
        git status -s || (git commit -m "NPM version update" && git push);
    - name: "Publish to NPM"
      run: npm publish --access public
