
name: Refreshes automatically-generated documentation

on:
  # On PR to `develop`
  pull_request:
    branches: [ main, develop ]
  # On demand
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: "Install Node"
      uses: actions/setup-node@v2
      with:
        node-version: "18"
    - name: "Install dependencies"
      run: npm install
    - name: "Run tests"
      run: npm run docgen
    - name: Commit changes
      run: |
        git config user.email "lil@law.harvard.edu"
        git config user.name "Github Actions"
        git commit -m "Auto doc update"
        git push origin develop
